const AboutPage = () => <div>
    <h1>App name</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis nibh vel mi tempus pretium. Sed nec blandit nulla. Proin magna metus, dictum vitae viverra nec, tincidunt vel est. Etiam molestie ultricies justo sed efficitur. Ut ultricies magna nec ligula tristique elementum. Nulla sed ante at lorem luctus vehicula nec eu elit. Phasellus ut blandit quam.

    Nunc ultrices dapibus justo, sed venenatis tellus sagittis sed. Maecenas molestie tellus metus, sit amet ultricies lorem tempus ac. Ut eget commodo ipsum. Sed sit amet volutpat turpis. Integer laoreet dignissim lacus non porta. Mauris auctor metus elit, ac faucibus turpis iaculis dapibus. Curabitur pretium leo nunc, ac tempor eros pellentesque quis. Donec sit amet rutrum felis.

    Duis sit amet erat sit amet sem lobortis iaculis. Donec fringilla, nibh a iaculis facilisis, purus risus finibus turpis, sit amet lobortis urna augue non ligula. Phasellus sed lobortis nibh. Nunc ac convallis metus. Quisque dignissim ligula nulla, a efficitur justo consequat vitae. Pellentesque posuere dolor vitae eros sollicitudin, ut egestas quam finibus. Phasellus nec purus a ipsum tincidunt tristique elementum vitae tortor. Maecenas ligula risus, gravida sed ante in, consequat pharetra lacus. Donec auctor lacinia risus nec molestie. Donec ligula velit, faucibus a eros et, rutrum eleifend velit. Nulla dolor velit, eleifend non ligula eu, elementum dignissim nunc. Etiam eu ultricies elit. Nulla eget vestibulum diam. Aenean vitae tortor sed felis suscipit pellentesque suscipit sed turpis. Aenean ut turpis a nibh consectetur mattis.

    Sed interdum ultrices ligula, id suscipit lacus tempus in. Donec vitae egestas ligula. Fusce sit amet pellentesque nunc, cursus feugiat leo. Nunc semper non felis ut sollicitudin. Etiam malesuada efficitur iaculis. Suspendisse tempus nisl et blandit scelerisque. Nulla id egestas erat, ac accumsan libero. Sed libero eros, finibus non faucibus facilisis, rhoncus vel felis. Curabitur convallis metus mi, in scelerisque ante aliquet id.

    Nunc vel mollis odio. In semper faucibus ultrices. Fusce nec diam aliquam tellus hendrerit sollicitudin. Nulla id nibh a tortor ultrices aliquam vitae placerat ipsum. Nulla enim lacus, placerat ac tincidunt et, ullamcorper sed mauris. Sed augue arcu, suscipit ac facilisis quis, posuere ut tellus. Donec quis sem at ante viverra laoreet. Morbi dignissim vitae dolor eget bibendum. Curabitur sagittis viverra mi, eget venenatis nisl ultricies quis. Nulla sed quam convallis, porta nunc nec, eleifend diam. Aenean eget massa diam. Donec pretium varius tincidunt. Nulla facilisi. Ut et magna mi. Vestibulum sit amet leo posuere, blandit tortor non, efficitur magna.</p>
</div>

export default AboutPage;